networks:
  - name: ethereum
    rpc_url: https://eth.llamarpc.com
  - name: base
    rpc_url: https://base.llamarpc.com

datafeeds:
  - name: eth_usd
    networks: ethereum
    check_frequency: 60
    contract_address: 0x1234567890123456789012345678901234567890
    contract_type: fluxmon
    read_contract_config: true
    minimum_update_frequency: 3600
    deviation_threshold_pct: 0.5
    feed_url: https://min-api.cryptocompare.com/data/pricemultifull?fsyms=ETH&tsyms=USD
    feed_json_path: RAW.ETH.USD.PRICE
    feed_json_path_timestamp: RAW.ETH.USD.LASTUPDATE
  - name: btc_usd
    networks: base
    check_frequency: 120
    contract_address: 0x0987654321098765432109876543210987654321
    contract_type: fluxmon
    read_contract_config: false
    decimals: 8
    min_value: 0
    max_value: 1000000
    minimum_update_frequency: 7200
    deviation_threshold_pct: 1.0
    feed_url: https://min-api.cryptocompare.com/data/pricemultifull?fsyms=BTC&tsyms=USD
    feed_json_path: RAW.BTC.USD.PRICE