networks:
  - name: local
    rpc_url: http://localhost:8545
    # Transaction type: "legacy" or "eip1559" (default: eip1559)
    transaction_type: eip1559
    
    # Gas configuration - see docs/gas-configuration.md for detailed explanation
    gas_config:
      # Basic settings with automatic estimation
      gas_multiplier: 1.2  # 20% safety margin on estimates
      
      # Fee bumping for stuck transactions
      fee_bumping:
        enabled: true
        max_retries: 3
        initial_wait_seconds: 30
        fee_increase_percent: 10.0
      
      # For manual overrides and advanced settings, see:
      # docs/gas-configuration.md#configuration-examples

datafeeds:
  - name: eth_usd
    networks: local
    check_frequency: 60
    contract_address: 0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0
    contract_type: fluxmon
    read_contract_config: true
    minimum_update_frequency: 3600
    deviation_threshold_pct: 0.5
    feed_url: https://min-api.cryptocompare.com/data/pricemultifull?fsyms=ETH&tsyms=USD
    feed_json_path: RAW.ETH.USD.PRICE
    feed_json_path_timestamp: RAW.ETH.USD.LASTUPDATE
    data_retention_days: 7  # Keep feed data for 7 days (default)

# Database cleanup configuration
database_cleanup:
  enabled: true              # Enable automatic cleanup (default: true)
  schedule: "0 0 * * * *"   # Cron schedule - every hour at minute 0 (default)

# Key storage configuration
key_storage:
  storage_type: env          # "keyring" or "env" (default: env for backward compatibility)
  keyring:
    service: omikuji         # Service name for keyring (default: omikuji)

# Metrics configuration
metrics:
  enabled: true              # Enable metrics collection (default: true)
  port: 9090                # Prometheus metrics port (default: 9090)
  detailed_metrics: false    # Enable high-cardinality metrics (default: false)
  categories:               # Enable/disable specific metric categories
    datasource: true        # Data source health metrics
    update_decisions: true  # Update decision tracking
    network: true          # Network/RPC metrics
    contract: true         # Contract interaction metrics
    quality: true          # Data quality metrics (requires detailed_metrics)
    economic: true         # Economic/cost tracking
    performance: true      # Performance metrics (requires detailed_metrics)
    config: true           # Configuration info metrics
    alerts: true           # Alert-worthy metrics