networks:
  - name: local
    rpc_url: http://localhost:8545
    # Transaction type: "legacy" or "eip1559" (default: eip1559)
    transaction_type: eip1559
    
    # Gas configuration - see docs/gas-configuration.md for detailed explanation
    gas_config:
      # Basic settings with automatic estimation
      gas_multiplier: 1.2  # 20% safety margin on estimates
      
      # Fee bumping for stuck transactions
      fee_bumping:
        enabled: true
        max_retries: 3
        initial_wait_seconds: 30
        fee_increase_percent: 10.0
      
      # For manual overrides and advanced settings, see:
      # docs/gas-configuration.md#configuration-examples

datafeeds:
  - name: eth_usd
    networks: local
    check_frequency: 60
    contract_address: 0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0
    contract_type: fluxmon
    read_contract_config: true
    minimum_update_frequency: 3600
    deviation_threshold_pct: 0.5
    feed_url: https://min-api.cryptocompare.com/data/pricemultifull?fsyms=ETH&tsyms=USD
    feed_json_path: RAW.ETH.USD.PRICE
    feed_json_path_timestamp: RAW.ETH.USD.LASTUPDATE